// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKlibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines the public facing task attributes
    /// </summary>
    public partial class TaskResultPayload
    {
        /// <summary>
        /// Initializes a new instance of the TaskResultPayload class.
        /// </summary>
        public TaskResultPayload() { }

        /// <summary>
        /// Initializes a new instance of the TaskResultPayload class.
        /// </summary>
        public TaskResultPayload(long? id = default(long?), string taskName = default(string), string dueDate = default(string), bool? isCompleted = default(bool?))
        {
            Id = id;
            TaskName = taskName;
            DueDate = dueDate;
            IsCompleted = isCompleted;
        }

        /// <summary>
        /// Gets or sets the task identifier.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or sets the task name
        /// </summary>
        [JsonProperty(PropertyName = "taskName")]
        public string TaskName { get; set; }

        /// <summary>
        /// Gets or sets Due date
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public string DueDate { get; set; }

        /// <summary>
        /// Gets or sets boolean value (true/false) to isCompleted
        /// </summary>
        [JsonProperty(PropertyName = "isCompleted")]
        public bool? IsCompleted { get; set; }

    }
}
